modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="entitylootdrops"
version="2.5"
displayName="Entity Loot Drops"
logoFile="assets/entitylootdrops/textures/gui/logo.png"
description='''
A mod that allows adding custom loot drops to entities with configurable drop rates.
'''
authors="Poe [Discord: AtPoe]"

[[dependencies.entitylootdrops]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.entitylootdrops]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

